<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIvs5knl\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIvs5knl/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIvs5knl.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerIvs5knl\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerIvs5knl\EccubeProdProjectContainer([
    'container.build_hash' => 'Ivs5knl',
    'container.build_id' => 'e5bf8cc9',
    'container.build_time' => 1619875734,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIvs5knl');
