<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNlj6qwg\EccubeDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNlj6qwg/EccubeDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNlj6qwg.legacy');

    return;
}

if (!\class_exists(EccubeDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNlj6qwg\EccubeDevDebugProjectContainer::class, EccubeDevDebugProjectContainer::class, false);
}

return new \ContainerNlj6qwg\EccubeDevDebugProjectContainer([
    'container.build_hash' => 'Nlj6qwg',
    'container.build_id' => 'ee686462',
    'container.build_time' => 1619875811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNlj6qwg');
